# After changing this file, check it on:
#   http://lint.travis-ci.org/

os:         linux
language:   python
env:        PYTHON_EXE=python

python:
    - 3.6
    - 3.7
    - 3.8
    - 3.9

jobs:
  include:
    - name: "Python 3 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7, but may change with time
      language: shell       # 'language: python' is an error on Travis CI macOS
      env: PYTHON_EXE=python3
    - name: "Python 3.8.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
        - ln -s `which python.exe` python3
      env:
        - PATH=/c/Python38:/c/Python38/Scripts:$PATH
        - PYTHON_EXE=python.exe

install:
    - CWD=`pwd`
    - PATH=$PATH:$CWD
    - THIS_REPO_NAME=`basename $CWD`
    - echo "TRAVIS_OS_NAME=${TRAVIS_OS_NAME}, TRAVIS_PYTHON_VERSION=${TRAVIS_PYTHON_VERSION}"
    - echo "CWD=${CWD}, THIS_REPO_NAME=${THIS_REPO_NAME}, PATH=${PATH}"
    - which ${PYTHON_EXE}
    - ${PYTHON_EXE} --version
    - wget https://raw.github.com/lehmannro/assert.sh/master/assert.sh

script:
    - my_asserts.sh
    - if [ "$TRAVIS_OS_NAME" == "windows" ]; then /usr/bin/env python3 --version ; fi
    - if [ "$TRAVIS_OS_NAME" == "windows" ]; then /usr/env python3 --version ; fi
    - if [ "$TRAVIS_OS_NAME" == "windows" ]; then which env ; fi
    - if [ "$TRAVIS_OS_NAME" == "windows" ]; then which python3 ; fi

