build: false

environment:
  ASSERT_URL: https://raw.github.com/lehmannro/assert.sh/master/assert.sh
  matrix:
    - job_name: Windows Py 3.6
      appveyor_build_worker_image: Visual Studio 2015
      PYTHON: C:\Python36-x64

    - job_name: Windows Py 3.9
      appveyor_build_worker_image: Visual Studio 2019
      PYTHON: C:\Python39-x64

    - job_name: MacOS Py 3.6
      appveyor_build_worker_image: macos
      stack: python 3.6

    - job_name: MacOS Py 3.9
      appveyor_build_worker_image: macos
      stack: python 3.9

    - job_name: Linux Py 3.6
      appveyor_build_worker_image: Ubuntu
      stack: python 3.6

    - job_name: Linux Py 3.9
      appveyor_build_worker_image: Ubuntu
      stack: python 3.9

init:
    - cmd: set PATH=%PYTHON%;%PYTHON%\\Scripts;%cd%;%PATH%
    - sh: export PATH=.:$PATH
    
install:
    - cmd: mklink python3.exe %PYTHON%\\python.exe
    - python3 --version
    - sh: python3.6 --version
    - sh: python3.8 --version
    - appveyor DownloadFile %ASSERT_URL%

test_script:
    - hello_world.py a b c d
    - cmd: hello_world A B C D
    - cmd: bash my_asserts.sh
    - sh: my_asserts.sh
