build: false

environment:
  matrix:
    - PYTHON: C:\Python36-x64
      PYTHON_VERSION: 3.6

#    - PYTHON: C:\Python35-x64
#      PYTHON_VERSION: 3.5

#    - PYTHON: C:\Python27-x64
#      PYTHON_VERSION: 2.7

init:
    - set PATH=%PYTHON%;%PYTHON%\\Scripts;%cd%;%PATH%
    - dir %PYTHON%
    - echo '==========='
    - dir %PYTHON%\\Scripts
    - echo '===================='
    - python --version

install:
    - appveyor DownloadFile https://raw.github.com/lehmannro/assert.sh/master/assert.sh

test_script:
    - python hello_world.py
    - bash my_asserts.sh
    - my_asserts.sh
