build: false

environment:
  matrix:
    - PYTHON: C:\Python36-x64
      PYTHON_VERSION: 3.6

#    - PYTHON: C:\Python35-x64
#      PYTHON_VERSION: 3.5

#    - PYTHON: C:\Python27-x64
#      PYTHON_VERSION: 2.7

init:
    - set PATH=%PYTHON%;%PYTHON%\\Scripts;%cd%;%PATH%

install:
    - mklink python3.exe %PYTHON%\\python.exe
    - python3 --version
    - appveyor DownloadFile https://raw.github.com/lehmannro/assert.sh/master/assert.sh

test_script:
    - hello_world.py
    - hello_world2
    - bash my_asserts.sh
