build: false

environment:
  matrix:
    - PYTHON: C:\Python36-x64
      PYTHON_VERSION: 3.6

#    - PYTHON: C:\Python35-x64
#      PYTHON_VERSION: 3.5

#    - PYTHON: C:\Python27-x64
#      PYTHON_VERSION: 2.7

init:
    - set PATH=%PYTHON%;%PYTHON%\\Scripts;%cd%;%PATH%
    - mklink python3.exe %PYTHON%\\python.exe
    - python --version
    - python3 --version

install:
    - appveyor DownloadFile https://raw.github.com/lehmannro/assert.sh/master/assert.sh

test_script:
    - python3 hello_world.py
    - bash my_asserts.sh
    - my_asserts.sh
